version: '3'
services:
  client:
    image: 'smilecraft/multi-client'
    mem_reservation: 128m
    hostname: client

  server:
    image: 'smilecraft/multi-server'
    mem_reservation: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: 'smilecraft/multi-worker'
    mem_reservation: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: 'smilecraft/multi-nginx'
    mem_reservation: 128m
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - server
      - client