name: Build

on:
  push:
    branches: [master]

jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build the Docker image
#        run: docker build -t knowable/react-test -f ./client/Dockerfile.dev ./client
#      - name: Run tests
#        run: docker run -e CI=true knowable/react-test npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:client"
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/multi-client:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

#      - name: Build the Client image
#        run: docker build -t knowable/multi-client ./client
#      - name: Build the Nginx image
#        run: docker build -t knowable/multi-nginx ./nginx
#      - name: Build the Server image
#        run: docker build -t knowable/multi-server ./server
#      - name: Build the Worker image
#        run: docker build -t knowable/multi-worker ./worker
